from __future__ import annotations

import subprocess
from pathlib import Path

import pytest

import test_bot.discover as discover_mod
from test_bot.discover import Target
from test_bot import main as main_mod


@pytest.fixture(autouse=True)
def _patch_repo_root(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setattr(discover_mod, "REPO_ROOT", tmp_path)


def _target(tmp_path: Path, language: str = "python") -> Target:
    app_dir = tmp_path / "app"
    source_path = app_dir / "src" / "module.py"
    test_path = app_dir / "tests" / "test_module.py"
    source_path.parent.mkdir(parents=True, exist_ok=True)
    source_path.write_text("def f():\n    return 1\n", encoding="utf-8")
    return Target(
        language=language,
        app="demo",
        app_dir=app_dir,
        source_path=source_path,
        test_path=test_path,
    )


def test_pr_body_contains_summary() -> None:
    summary = "- `tests/test_x.py` (covers `src/x.py`)"
    body = main_mod._pr_body(summary)
    assert "Automated unit tests generated by [test-bot]" in body
    assert summary in body


def test_github_output_writes_single_and_multiline(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    output = tmp_path / "github_output.txt"
    monkeypatch.setenv("GITHUB_OUTPUT", str(output))

    main_mod._github_output("branch", "test-branch")
    main_mod._github_output("body", "line1\nline2")

    text = output.read_text(encoding="utf-8")
    assert "branch=test-branch" in text
    assert "body<<EOF\nline1\nline2\nEOF" in text


def test_generate_and_verify_success_first_try(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    target = _target(tmp_path)
    writes: list[str] = []

    monkeypatch.setattr(main_mod, "generate_test_content", lambda _target, fix_error=None: "ok\n")
    monkeypatch.setattr(
        main_mod,
        "write_test_file",
        lambda t, c, dry_run: (t.test_path.parent.mkdir(parents=True, exist_ok=True), t.test_path.write_text(c, encoding="utf-8"), writes.append(c)),
    )
    monkeypatch.setattr(main_mod, "_run_tests_for_target", lambda _target: None)

    assert main_mod._generate_and_verify(target, max_attempts=2) is True
    assert target.test_path.is_file()
    assert writes == ["ok\n"]


def test_generate_and_verify_retries_with_fix_error(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    target = _target(tmp_path)
    seen_fix_errors: list[str | None] = []
    call_count = 0

    def _fake_generate(_target: Target, *, fix_error: str | None = None) -> str:
        seen_fix_errors.append(fix_error)
        return "content\n"

    def _fake_write(t: Target, content: str, *, dry_run: bool) -> None:
        t.test_path.parent.mkdir(parents=True, exist_ok=True)
        t.test_path.write_text(content, encoding="utf-8")

    def _fake_run(_target: Target) -> None:
        nonlocal call_count
        call_count += 1
        if call_count == 1:
            raise subprocess.CalledProcessError(1, ["pytest"], output="stdout", stderr="stderr")

    monkeypatch.setattr(main_mod, "generate_test_content", _fake_generate)
    monkeypatch.setattr(main_mod, "write_test_file", _fake_write)
    monkeypatch.setattr(main_mod, "_run_tests_for_target", _fake_run)

    assert main_mod._generate_and_verify(target, max_attempts=2) is True
    assert seen_fix_errors[0] is None
    assert seen_fix_errors[1] is not None
    assert "stderr" in seen_fix_errors[1]
    assert call_count == 2


def test_generate_and_verify_cleans_up_failed_file(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    target = _target(tmp_path)

    monkeypatch.setattr(main_mod, "generate_test_content", lambda _target, fix_error=None: "bad\n")
    monkeypatch.setattr(
        main_mod,
        "write_test_file",
        lambda t, c, dry_run: (t.test_path.parent.mkdir(parents=True, exist_ok=True), t.test_path.write_text(c, encoding="utf-8")),
    )
    monkeypatch.setattr(
        main_mod,
        "_run_tests_for_target",
        lambda _target: (_ for _ in ()).throw(
            subprocess.CalledProcessError(1, ["pytest"], output="out", stderr="err")
        ),
    )

    assert main_mod._generate_and_verify(target, max_attempts=2) is False
    assert not target.test_path.exists()


def test_main_returns_when_no_targets(
    monkeypatch: pytest.MonkeyPatch, capsys: pytest.CaptureFixture[str]
) -> None:
    monkeypatch.setattr(main_mod, "discover_targets", lambda max_targets: [])
    monkeypatch.setattr(main_mod.sys, "argv", ["test-bot"])
    main_mod.main()
    out = capsys.readouterr().out
    assert "No uncovered source files found" in out


def test_main_dry_run_skips_generation(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch, capsys: pytest.CaptureFixture[str]
) -> None:
    target = _target(tmp_path)
    monkeypatch.setattr(main_mod, "discover_targets", lambda max_targets: [target])
    monkeypatch.setattr(main_mod.sys, "argv", ["test-bot", "--dry-run"])

    def _fail(*args: object, **kwargs: object) -> None:
        raise AssertionError("generation should not run in dry-run mode")

    monkeypatch.setattr(main_mod, "_generate_and_verify", _fail)
    main_mod.main()
    out = capsys.readouterr().out
    assert "Dry run complete" in out
